CREATE TYPE "public"."card-golf_game_status" AS ENUM('waiting', 'setup', 'playing', 'final_turn', 'round_ended', 'finished', 'abandoned');--> statement-breakpoint
CREATE TABLE "card-golf_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "card-golf_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "card-golf_game_player" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"gameId" uuid NOT NULL,
	"userId" varchar(255) NOT NULL,
	"playerIndex" integer NOT NULL,
	"hand" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"revealedCount" integer DEFAULT 0 NOT NULL,
	"totalScore" integer DEFAULT 0 NOT NULL,
	"setupComplete" boolean DEFAULT false NOT NULL,
	"displayName" varchar(255) NOT NULL,
	"isGuest" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "card-golf_game" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"code" varchar(8) NOT NULL,
	"status" "card-golf_game_status" DEFAULT 'waiting' NOT NULL,
	"config" jsonb NOT NULL,
	"currentRound" integer DEFAULT 1 NOT NULL,
	"currentPlayerIndex" integer DEFAULT 0 NOT NULL,
	"turnNumber" integer DEFAULT 0 NOT NULL,
	"deck" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"discardPile" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"drawnCard" varchar(2),
	"finishTriggeredBy" varchar(255),
	"finalTurnPlayersRemaining" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"dealerIndex" integer DEFAULT 0 NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "card-golf_guest_player" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"displayName" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "card-golf_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "card-golf_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "card-golf_round_score" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"gameId" uuid NOT NULL,
	"playerId" uuid NOT NULL,
	"roundNumber" integer NOT NULL,
	"score" integer NOT NULL,
	"hand" jsonb NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "card-golf_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "card-golf_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "card-golf_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "card-golf_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "card-golf_account" ADD CONSTRAINT "card-golf_account_userId_card-golf_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."card-golf_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "card-golf_game_player" ADD CONSTRAINT "card-golf_game_player_gameId_card-golf_game_id_fk" FOREIGN KEY ("gameId") REFERENCES "public"."card-golf_game"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "card-golf_post" ADD CONSTRAINT "card-golf_post_createdById_card-golf_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."card-golf_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "card-golf_round_score" ADD CONSTRAINT "card-golf_round_score_gameId_card-golf_game_id_fk" FOREIGN KEY ("gameId") REFERENCES "public"."card-golf_game"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "card-golf_round_score" ADD CONSTRAINT "card-golf_round_score_playerId_card-golf_game_player_id_fk" FOREIGN KEY ("playerId") REFERENCES "public"."card-golf_game_player"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "card-golf_session" ADD CONSTRAINT "card-golf_session_userId_card-golf_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."card-golf_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "card-golf_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "game_player_game_idx" ON "card-golf_game_player" USING btree ("gameId");--> statement-breakpoint
CREATE INDEX "game_player_user_idx" ON "card-golf_game_player" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "game_code_idx" ON "card-golf_game" USING btree ("code");--> statement-breakpoint
CREATE INDEX "game_status_idx" ON "card-golf_game" USING btree ("status");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "card-golf_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "card-golf_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "round_score_game_idx" ON "card-golf_round_score" USING btree ("gameId");--> statement-breakpoint
CREATE INDEX "round_score_player_idx" ON "card-golf_round_score" USING btree ("playerId");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "card-golf_session" USING btree ("userId");